# Generated by Django 4.2.6 on 2023-12-26 12:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="video_file",
            field=models.FileField(upload_to="media/main"),
        ),
    ]
