# Generated by Django 4.2.6 on 2024-01-08 18:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_alter_video_video_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="encoding_status",
            field=models.CharField(default="Not encoding", max_length=100),
        ),
    ]
